name: Production workflow

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install

      - name: Build packages
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build

      - name: Authenticate with Registry
        run: |
          yarn logout
          echo "@smarterlabs:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}


      - name: Publish packages to npm
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: publish:production
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}